### ISSUE TITLE
Trying to work with GraphQL but limited documentation

### ISSUE THREAD

**Issue by onepack** [ergonode/backend#1880]
* Community Chat: Links: [discord](https://discord.gg/NntXFa4)
* Twitter: If it's just a quick question you can ping our [Twitter](https://twitter.com/ergonode)

I'm working on the development of an new integration with Ergonode via GraphQL and I'm successfully creating products in Ergonode.
However I'm running into a lack of documentation or examples.

Following this example and some others I can create a simple product via Postman.
https://docs.ergonode.com/v/graphql-api/query-examples/create-a-product-and-assign-modify-attributes-values

However, when I change the productAddAttributeValueTranslationsText to productAddAttributeValueTranslationsTextarea it stops working. I tried all sorts of approaches but they all seem to fail.
How to fill two textarea attrubutes while creating the product?

mutation {
  productCreateSimple(input: { sku: "new_product", templateCode: "template" }) {
    __typename
  }
  productAddAttributeValueTranslationsTextarea(
    input: {
      sku: "new_product"
      attributeCode: "description"
      translations: [{ value: "Main Description", language: "en_GB" }]
    }
  ) {
    __typename
  }
  productAddAttributeValueTranslationsTextarea(
    input: {
      sku: "new_product"
      attributeCode: "short_description"
      translations: [{ value: "Short Description", language: "en_GB" }]
    }
  ) {
    __typename
  }
}

**Comment by piotrkreft** [comment]
@onepack in general your example looks correct - perhaps the issue is mismatched attribute type or similar - the validation message should hint you the right way. However, if still unobvious please get in touch with support via [issues.ergonode.com](https://ergonodesupport.atlassian.net/servicedesk/customer/user/login?destination=portals) or via Community Ergonode Slack - they'll help you based on your actual instance data.
This is an obsolete repository and maintained anymore.
Best of luck!
